/*
 * codeBeamer swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Reference to a field of a tracker
 */
@ApiModel(description = "Reference to a field of a tracker")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2018-12-02T20:31:20.747+01:00[Europe/Budapest]")

public class AbstractFieldReference {
  public static final String SERIALIZED_NAME_FIELD_ID = "fieldId";
  @SerializedName(SERIALIZED_NAME_FIELD_ID)
  private Integer fieldId;

  public static final String SERIALIZED_NAME_TRACKER_ID = "trackerId";
  @SerializedName(SERIALIZED_NAME_TRACKER_ID)
  private Integer trackerId;

  public static final String SERIALIZED_NAME_URI = "uri";
  @SerializedName(SERIALIZED_NAME_URI)
  private String uri;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public AbstractFieldReference() {
    this.type = this.getClass().getSimpleName();
  }
  public AbstractFieldReference fieldId(Integer fieldId) {
    this.fieldId = fieldId;
    return this;
  }

   /**
   * ID of a object
   * @return fieldId
  **/
  @ApiModelProperty(value = "ID of a object")
  public Integer getFieldId() {
    return fieldId;
  }

  public void setFieldId(Integer fieldId) {
    this.fieldId = fieldId;
  }

  public AbstractFieldReference trackerId(Integer trackerId) {
    this.trackerId = trackerId;
    return this;
  }

   /**
   * ID of a tracker
   * @return trackerId
  **/
  @ApiModelProperty(value = "ID of a tracker")
  public Integer getTrackerId() {
    return trackerId;
  }

  public void setTrackerId(Integer trackerId) {
    this.trackerId = trackerId;
  }

  public AbstractFieldReference uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * Reference of a object
   * @return uri
  **/
  @ApiModelProperty(value = "Reference of a object")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  public AbstractFieldReference type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Type of a referenced object
   * @return type
  **/
  @ApiModelProperty(value = "Type of a referenced object")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AbstractFieldReference abstractFieldReference = (AbstractFieldReference) o;
    return Objects.equals(this.fieldId, abstractFieldReference.fieldId) &&
        Objects.equals(this.trackerId, abstractFieldReference.trackerId) &&
        Objects.equals(this.uri, abstractFieldReference.uri) &&
        Objects.equals(this.type, abstractFieldReference.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fieldId, trackerId, uri, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AbstractFieldReference {\n");
    
    sb.append("    fieldId: ").append(toIndentedString(fieldId)).append("\n");
    sb.append("    trackerId: ").append(toIndentedString(trackerId)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

