/*
 * codeBeamer swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.intland.swagger.demo;

import com.intland.swagger.ApiException;
import org.openapitools.client.model.Comment;
import java.io.File;
import org.openapitools.client.model.InternalServerErrorException;
import org.openapitools.client.model.ResourceForbiddenException;
import org.openapitools.client.model.ResourceNotFoundException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TrackerItemsCommentApi
 */
@Ignore
public class TrackerItemsCommentApiTest {

    private final TrackerItemsCommentApi api = new TrackerItemsCommentApi();

    
    /**
     * Delete comment of tracker item by id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v2ItemItemIdCommentCommentIdDeleteTest() throws ApiException {
        Integer itemId = null;
        Integer commentId = null;
        Comment response = api.v2ItemItemIdCommentCommentIdDelete(itemId, commentId);

        // TODO: test validations
    }
    
    /**
     * Get comment of tracker item by id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v2ItemItemIdCommentCommentIdGetTest() throws ApiException {
        Integer itemId = null;
        Integer commentId = null;
        Comment response = api.v2ItemItemIdCommentCommentIdGet(itemId, commentId);

        // TODO: test validations
    }
    
    /**
     * Reply on a comment of a tracker item
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v2ItemItemIdCommentCommentIdPostTest() throws ApiException {
        Integer itemId = null;
        Integer commentId = null;
        String comment = null;
        String commentFormat = null;
        File attachments = null;
        Comment response = api.v2ItemItemIdCommentCommentIdPost(itemId, commentId, comment, commentFormat, attachments);

        // TODO: test validations
    }
    
    /**
     * Edit comment on a tracker item
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v2ItemItemIdCommentCommentIdPutTest() throws ApiException {
        Integer itemId = null;
        Integer commentId = null;
        String comment = null;
        String commentFormat = null;
        File attachments = null;
        Comment response = api.v2ItemItemIdCommentCommentIdPut(itemId, commentId, comment, commentFormat, attachments);

        // TODO: test validations
    }
    
    /**
     * Comment on a tracker item
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v2ItemItemIdCommentPostTest() throws ApiException {
        Integer itemId = null;
        String comment = null;
        String commentFormat = null;
        File attachments = null;
        Comment response = api.v2ItemItemIdCommentPost(itemId, comment, commentFormat, attachments);

        // TODO: test validations
    }
    
}
