/*
 * codeBeamer swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.intland.swagger.demo;

import com.intland.swagger.ApiException;
import org.openapitools.client.model.ResourceForbiddenException;
import org.openapitools.client.model.ResourceNotFoundException;
import org.openapitools.client.model.UserGroup;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GroupApi
 */
@Ignore
public class GroupApiTest {

    private final GroupApi api = new GroupApi();

    
    /**
     * Get user groups
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v2UserGroupGetTest() throws ApiException {
        List<UserGroup> response = api.v2UserGroupGet();

        // TODO: test validations
    }
    
    /**
     * Get user group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v2UserGroupGroupIdGetTest() throws ApiException {
        Integer groupId = null;
        UserGroup response = api.v2UserGroupGroupIdGet(groupId);

        // TODO: test validations
    }
    
}
