/*
 * codeBeamer swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.intland.swagger.demo;

import com.intland.swagger.ApiException;
import org.openapitools.client.model.Attachment;
import java.io.File;
import org.openapitools.client.model.ResourceForbiddenException;
import org.openapitools.client.model.ResourceNotFoundException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TrackerItemsAttachmentApi
 */
@Ignore
public class TrackerItemsAttachmentApiTest {

    private final TrackerItemsAttachmentApi api = new TrackerItemsAttachmentApi();

    
    /**
     * Get content of an attachment of tracker item by id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v2ItemItemIdAttachmentAttachmentIdContentGetTest() throws ApiException {
        Integer itemId = null;
        Integer attachmentId = null;
        File response = api.v2ItemItemIdAttachmentAttachmentIdContentGet(itemId, attachmentId);

        // TODO: test validations
    }
    
    /**
     * Delete attachment of tracker item by id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v2ItemItemIdAttachmentAttachmentIdDeleteTest() throws ApiException {
        Integer itemId = null;
        Integer attachmentId = null;
        Attachment response = api.v2ItemItemIdAttachmentAttachmentIdDelete(itemId, attachmentId);

        // TODO: test validations
    }
    
    /**
     * Get attachment of tracker item by id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v2ItemItemIdAttachmentAttachmentIdGetTest() throws ApiException {
        Integer itemId = null;
        Integer attachmentId = null;
        Attachment response = api.v2ItemItemIdAttachmentAttachmentIdGet(itemId, attachmentId);

        // TODO: test validations
    }
    
    /**
     * Delete attachments of tracker item
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v2ItemItemIdAttachmentDeleteTest() throws ApiException {
        Integer itemId = null;
        api.v2ItemItemIdAttachmentDelete(itemId);

        // TODO: test validations
    }
    
    /**
     * Get attachments of tracker item
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v2ItemItemIdAttachmentGetTest() throws ApiException {
        Integer itemId = null;
        List<Attachment> response = api.v2ItemItemIdAttachmentGet(itemId);

        // TODO: test validations
    }
    
    /**
     * Upload an attachment to a tracker item
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v2ItemItemIdAttachmentPostTest() throws ApiException {
        Integer itemId = null;
        File attachments = null;
        List<Attachment> response = api.v2ItemItemIdAttachmentPost(itemId, attachments);

        // TODO: test validations
    }
    
}
