/*
 * codeBeamer swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.intland.swagger.demo;

import com.intland.swagger.ApiException;
import org.openapitools.client.model.Comment;
import org.openapitools.client.model.ResourceForbiddenException;
import org.openapitools.client.model.ResourceNotFoundException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TrackerItemsCommentsApi
 */
@Ignore
public class TrackerItemsCommentsApiTest {

    private final TrackerItemsCommentsApi api = new TrackerItemsCommentsApi();

    
    /**
     * Delete comments of tracker item by id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v2ItemItemIdCommentDeleteTest() throws ApiException {
        Integer itemId = null;
        api.v2ItemItemIdCommentDelete(itemId);

        // TODO: test validations
    }
    
    /**
     * Get comments of tracker item
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v2ItemItemIdCommentGetTest() throws ApiException {
        Integer itemId = null;
        List<Comment> response = api.v2ItemItemIdCommentGet(itemId);

        // TODO: test validations
    }
    
}
