/*
 * codeBeamer swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.List;

import io.swagger.annotations.ApiModel;
import org.openapitools.client.model.AbstractChoiceField;

import com.google.gson.annotations.SerializedName;

/**
 * Option type choice field
 */
@ApiModel(description = "Option type choice field")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2018-12-02T20:31:20.747+01:00[Europe/Budapest]")
public class OptionChoiceField extends AbstractChoiceField {

	public static final String SERIALIZED_NAME_HIDDEN = "options";
	@SerializedName(SERIALIZED_NAME_HIDDEN)
	private List<ChoiceOptionReference> options;

	public List<ChoiceOptionReference> getOptions() {
		return options;
	}

	public void setOptions(List<ChoiceOptionReference> options) {
		this.options = options;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		return super.equals(o);
	}

	@Override
	public int hashCode() {
		return Objects.hash(super.hashCode());
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class OptionChoiceField {\n");
		sb.append("    ").append(toIndentedString(super.toString())).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
